# permissions for end users to edit configurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configuration-editor-role
rules:
- apiGroups:
  - authcontroller.intel.com
  resources:
  - configurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authcontroller.intel.com
  resources:
  - configurations/status
  verbs:
  - get
